### ISSUE TITLE
The face3d render function doesn't work

### ISSUE THREAD

**Issue by fantasy-fish** [pengbo-learn/python-face-relighting#4] opened 2020-03-28 01:24 UTC
It seems the face3d render function doesn't work for the PRnet vertices.
Instead I used the render function provided in the original PRNet implementation to make it work.

Specifically, I made the changes below in relight.py
from
`from .face3d.face3d.mesh.render import render_colors as render_texture`
to
`from .PRNet.utils.render import render_texture`

**Comment by pengbo-learn** [comment] 2020-03-28 01:44
> It seems the face3d render function doesn't work for the PRnet vertices.
> Instead I used the render function provided in the original PRNet implementation to make it work.
> 
> Specifically, I made the changes below in relight.py
> from
> `from .face3d.face3d.mesh.render import render_colors as render_texture`
> to
> `from .PRNet.utils.render import render_texture`

clone this repo https://github.com/YadiraF/face3d.git

**Comment by fantasy-fish** [comment] 2020-03-28 01:53
I already cloned it, but the result isn't correct. The result is a totally black image, and there's only a few white pixels in the face mask image. Maybe there's some problem with the coordinate system.

Currently, I am using the render function provided in the original PRNet implementation, and everything is good.

**Comment by tachikoma777** [comment] 2021-05-24 12:22
I met similar problem, the provided code output the same pic as input, after I change to "from .PRNet.utils.render import render_texture", the result is normal, however timecost it 36s, don't know whether its too long

**Comment by pengbo-learn** [comment] 2021-05-27 02:28
face3d is now merged into the latest commit. 

Current time cost is 30s+, most of the time is spent in render_texture. 

The reported time in former commit was about 5s, I lost the running environments and failed to achieve this timing results again. Not sure it's caused by the difference in the running machine or the versions of the environments.

**Closed as completed** 2022-04-02 08:39 UTC

**Comment by pengbo-learn** [comment] 2022-05-31 13:06
> face3d is now merged into the latest commit.
> 
> Current time cost is 30s+, most of the time is spent in render_texture.
> 
> The reported time in former commit was about 5s, I lost the running environments and failed to achieve this timing results again. Not sure it's caused by the difference in the running machine or the versions of the environments.

The cause of differences in timing has been found. face3d has 2 versions of rendering, one is based on c++, the other is based on numpy. Now both implementations have been included, the version of rendering could be specified by set flag fast=True or fast=False in demo.py.
